server:
  port: 8080
  tomcat:
    connection-timeout: 30000

spring:
  datasource:
    url: jdbc:mysql://39.106.153.222:3306/draw?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: remote
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.draw.entity
  configuration:
    map-underscore-to-camel-case: true

# 测试环境可以先不配置微信相关信息
#wx:
#  miniapp:
#    appid: 你的小程序appid
#    secret: 你的小程序secret 